<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Lms.SharedKernel\Lms.SharedKernel.csproj" />
    <ProjectReference Include="..\..\Lms.SharedKernel.Persistence\Lms.SharedKernel.Persistence.csproj" />
    <ProjectReference Include="..\..\Lms.SharedKernel.Http\Lms.SharedKernel.Http.csproj" />
    <ProjectReference Include="..\Lms.Modules.Identity.Contracts\Lms.Modules.Identity.Contracts.csproj" />
  </ItemGroup>

</Project>
